export default {
    lookingForPatients: false,
    lookingForPatientsError: null,
    patients: [],
    allergyLoading: false,
    allergyError: null,
    allergyIntolerance: [],
    allergyCount: 0,
    loadingCarePlan: false,
    carePlanError: null,
    carePlan: [],
    carePlanCount: 0,
    loadingCareTeam: false,
    careTeam: [],
    careTeamCount: 0,
    loadingCondition: false,
    condition: [],
    conditionError: null,
    conditionCount: 0,
    loadingDiagnosticReport: false,
    diagnosticReportError: null,
    diagnosticReportCount: 0,
    diagnosticReport:[],
    loadingEncounter: false,
    encounterError: null,
    encounterCount: 0,
    encounter: [],
    goalError: null,
    goalCount: 0,
    goal: [],
    loadingGoal: false,
    immunizationError: null,
    immunizationCount: 0,
    immunization: [],
    loadingImmunization: false,
    medicationDispenseError: null,
    medicationDispenseCount: 0,
    medicationDispense: [],
    loadingMedicationDispense: false,
    medicationRequestError: null,
    medicationRequestCount: 0,
    medicationRequest: [],
    loadingMedicationRequest: false,
    observation: [],
    observationError: null,
    observationCount: 0,
    loadingObservation: false,
    procedureError: null,
    procedureCount:0,
    procedure:[],
    loadingProcedure: false,
    procedureRequestError: null,
    procedureRequestCount:0,
    procedureRequest: [],
    loadingProcedureRequest:false
}
