const meta = {
    parsed: {
        version: "0.0.0",
        capabilities: {
            Account: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            AllergyIntolerance: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Appointment: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            AppointmentResponse: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            AuditEvent: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Basic: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Binary: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            BodySite: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Bundle: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            CarePlan: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Claim: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            ClaimResponse: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            ClinicalImpression: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Communication: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            CommunicationRequest: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Composition: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            ConceptMap: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Condition: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Conformance: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Contract: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Coverage: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            DataElement: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            DetectedIssue: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Device: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            DeviceComponent: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            DeviceMetric: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            DeviceUseRequest: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            DeviceUseStatement: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            DiagnosticOrder: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            DiagnosticReport: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            DocumentManifest: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            DocumentReference: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Documentation: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            EligibilityRequest: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            EligibilityResponse: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Encounter: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            EnrollmentRequest: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            EnrollmentResponse: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            EpisodeOfCare: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            ExplanationOfBenefit: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            FamilyMemberHistory: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Flag: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Goal: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Group: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            HealthcareService: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            ImagingObjectSelection: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            ImagingStudy: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Immunization: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            ImmunizationRecommendation: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            ImplementationGuide: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            List: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Location: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Media: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Medication: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            MedicationAdministration: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            MedicationDispense: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            MedicationOrder: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            MedicationStatement: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            MessageHeader: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            NamingSystem: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            NutritionOrder: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Observation: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            OperationDefinition: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            OperationOutcome: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Order: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            OrderResponse: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Organization: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Parameters: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Patient: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            PaymentNotice: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            PaymentReconciliation: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Person: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Practitioner: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Procedure: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            ProcedureRequest: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            ProcessRequest: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            ProcessResponse: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Provenance: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Questionnaire: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            QuestionnaireResponse: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            ReferralRequest: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            RelatedPerson: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Remittance: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            RiskAssessment: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Schedule: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            SearchParameter: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Slot: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Specimen: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            StructureDefinition: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Subscription: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Substance: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            SupplyDelivery: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            SupplyRequest: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            SupportingDocumentation: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            Test: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            TestScript: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            User: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            ValueSet: {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
            VisionPrescription:
            {
                read: false,
                vread: false,
                update: false,
                delete: false,
                historyInstance: false,
                historyType: false,
                create: false,
                searchType: false,
            },
        },
    },
    raw: {},
    status: "ready",
};

export default [
    {
        smart: {
            status: "demo-mode",
            data: {
                patient: {
                    id: "SMART-0002",
                    api: {},
                },
            },
        },
        parsed: {
            needPatientBanner: true,
            patientDemographics: {
                status: "ready",
                data: {
                    birthDate: "1910-01-01",
                    gender:    "female",
                    MRN:       "0002-SAMPLE-MRN",
                    name:      "Jan Z. Doe",
                    smartId:   "SMART-0002",
                    address: [
                        { use: "home", val: "Somewhere" },
                    ],
                    email: [
                        { val: "jan@example.com" },
                    ],
                    names: [
                        { use: "Official", val: "Jan Doe" },
                    ],
                    phone: [
                        { use: "home", val: "000-000-001" },
                    ],
                },
            },
        },
        meta,
    },

    {
        smart: {
            status: "demo-mode",
            data: {
                patient: {
                    id: "SMART-0001",
                    api: {},
                },
            },
        },
        parsed: {
            needPatientBanner: true,
            patientDemographics: {
                status: "ready",
                data: {
                    birthDate: "1900-01-01",
                    gender:    "female",
                    MRN:       "0001-SAMPLE-MRN",
                    name:      "Jane Z. Doe",
                    smartId:   "SMART-0001",
                    address: [
                        { use: "home", val: "Somewhere" },
                    ],
                    email: [
                        { val: "jane@example.com" },
                    ],
                    names: [
                        { use: "Official", val: "Jane Doe" },
                    ],
                    phone: [
                        { use: "home", val: "000-000-001" },
                    ],
                },
            },
        },
        meta,
    },

    {
        smart: {
            status: "demo-mode",
            data: {
                tokenResponse: {},
                patient: {
                    id: "SMART-0000",
                    api: {},
                },
            },
        },
        parsed: {
            needPatientBanner: true,
            patientDemographics: {
                status: "ready",
                data: {
                    birthDate: "1900-01-01",
                    gender:    "male",
                    MRN:       "0000-SAMPLE",
                    name:      "John Y. Doe",
                    smartId:   "SMART-0000",
                    address: [
                        { use: "home", val: "Somewhere" },
                    ],
                    email: [
                        { val: "john@example.com" },
                    ],
                    names: [
                        { use: "Official", val: "John Doe" },
                    ],
                    phone: [
                        { use: "home", val: "000-000-000" },
                    ],
                },
            },
        },
        meta,
    },

];
